# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UluTcy2ksrFT/s4UdLQU23gc4kvIXrObxwpD9DREnTRFsyaIzkVNVflVqwUAYF3DOmY3l6nkkC/PI4tFXfRts/NWGNKN6AA9ww03W1n1RH2x5rrea0F3UdbhsM0My3hIbrWTevkLUZIvMEbaJ0UHNBjlaX1KsrL6/Fr9CncSa+GsiSgvVNEfqgi+jTdF3YQgtcjc+uyfiZMLdOc3H046us5O1euE8TgbUXRgeeXADzVrk+Mwjzxu+vni2nOhItX6yzVCdvi3RbGLHDJfPv50ckgycMZCzGv0c3ESB/NbvuEoSI/1Bt1+VxGc32YrUm+JaGDp25BGyZ+Jx2tn+qj9VUNaVVaucP1V0lsh/jZ1buqzhj/oSZUPmLYAuu+qtnUcgDSrl28V66l7n40pTmz1NWEq8pz75z4bItLCjrnXdJuB4cy852vqiu1N68W0tH49BQQXdi7DVARHU5Z3qrQL/3cyWHropQgbfioImM+8/n09OJPJ9td1nab3Dc9YnF4NGiY/Kv470mvQqcD7PBkkoTAn5Ifi7U4DR1fSfpDLK+lFmdo21suTkTvvs5QjgD4b22KaRlm8sY0Gk9xBrcDmAQjgWUIc0S24CtOoD3bHZ49qj60zEHQoa7rp2L6GUgPxbjYFFQg4M8udUk2GTQheMw8+JphlgbOsNasz5EqBjlc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
