travis:
  secure:
    BINSTAR_TOKEN: UluTcy2ksrFT/s4UdLQU23gc4kvIXrObxwpD9DREnTRFsyaIzkVNVflVqwUAYF3DOmY3l6nkkC/PI4tFXfRts/NWGNKN6AA9ww03W1n1RH2x5rrea0F3UdbhsM0My3hIbrWTevkLUZIvMEbaJ0UHNBjlaX1KsrL6/Fr9CncSa+GsiSgvVNEfqgi+jTdF3YQgtcjc+uyfiZMLdOc3H046us5O1euE8TgbUXRgeeXADzVrk+Mwjzxu+vni2nOhItX6yzVCdvi3RbGLHDJfPv50ckgycMZCzGv0c3ESB/NbvuEoSI/1Bt1+VxGc32YrUm+JaGDp25BGyZ+Jx2tn+qj9VUNaVVaucP1V0lsh/jZ1buqzhj/oSZUPmLYAuu+qtnUcgDSrl28V66l7n40pTmz1NWEq8pz75z4bItLCjrnXdJuB4cy852vqiu1N68W0tH49BQQXdi7DVARHU5Z3qrQL/3cyWHropQgbfioImM+8/n09OJPJ9td1nab3Dc9YnF4NGiY/Kv470mvQqcD7PBkkoTAn5Ifi7U4DR1fSfpDLK+lFmdo21suTkTvvs5QjgD4b22KaRlm8sY0Gk9xBrcDmAQjgWUIc0S24CtOoD3bHZ49qj60zEHQoa7rp2L6GUgPxbjYFFQg4M8udUk2GTQheMw8+JphlgbOsNasz5EqBjlc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
